import React, { useState, useRef, type ChangeEvent } from 'react';
import { Helmet } from "react-helmet-async";
import ToolLayout from '../../layout/ToolLayout.tsx';
import { LayoutGrid, Image as ImageIcon, RefreshCw, Loader2, CheckCircle2 } from 'lucide-react';
import JSZip from 'jszip';

const InstagramGridMaker: React.FC = () => {
    const [previewUrl, setPreviewUrl] = useState<string | null>(null);
    const [fileName, setFileName] = useState<string>("grid");
    const [isProcessing, setIsProcessing] = useState(false);
    const [isDone, setIsDone] = useState(false);
    const canvasRef = useRef<HTMLCanvasElement>(null);

    // Grid size configuration
    const GRID_ROWS = 3;
    const GRID_COLS = 3;

    const handleImageUpload = (e: ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            setFileName(file.name.split('.')[0]);
            setPreviewUrl(URL.createObjectURL(file));
            setIsDone(false);
        }
    };

    const generateGridFiles = async () => {
        if (!previewUrl || !canvasRef.current) return;
        setIsProcessing(true);

        const zip = new JSZip();
        const canvas = canvasRef.current;
        const ctx = canvas.getContext('2d');
        const img = new Image();
        img.src = previewUrl;

        await new Promise((resolve) => {
            img.onload = async () => {
                // Determine the square size based on the smaller dimension
                const sourceSize = Math.min(img.width, img.height);
                const sourceX = (img.width - sourceSize) / 2;
                const sourceY = (img.height - sourceSize) / 2;

                // High-resolution output tile size (e.g., 1080p per tile)
                const TILE_SIZE = 1080;
                canvas.width = TILE_SIZE;
                canvas.height = TILE_SIZE;

                const sourceTileSize = sourceSize / GRID_COLS;

                for (let row = 0; row < GRID_ROWS; row++) {
                    for (let col = 0; col < GRID_COLS; col++) {
                        if (ctx) {
                            ctx.clearRect(0, 0, TILE_SIZE, TILE_SIZE);

                            // Advanced canvas drawing with high-quality scaling
                            ctx.imageSmoothingEnabled = true;
                            ctx.imageSmoothingQuality = 'high';

                            // Draw the specific part of the image to the square canvas
                            ctx.drawImage(
                                img,
                                sourceX + (col * sourceTileSize), // Source X
                                sourceY + (row * sourceTileSize), // Source Y
                                sourceTileSize, // Source Width
                                sourceTileSize, // Source Height
                                0, // Destination X
                                0, // Destination Y
                                TILE_SIZE, // Destination Width
                                TILE_SIZE  // Destination Height
                            );

                            // Convert canvas to blob (PNG for high quality)
                            const blob = await new Promise<Blob | null>((res) => canvas.toBlob(res, 'image/png', 0.9));
                            if (blob) {
                                // Name files sequentially based on Instagram upload order (top-left to bottom-right)
                                const tileNumber = (row * GRID_COLS) + col + 1;
                                zip.file(`njtools-grid-${fileName}-tile-${tileNumber}.png`, blob);
                            }
                        }
                    }
                }

                const readme = `
                NJTools Instagram Grid Maker
                ============================
                Your image has been split into a 3x3 grid (9 tiles).

                How to upload to Instagram:
                ---------------------------
                To get the perfect grid on your profile, upload the images in REVERSE sequential order:
                1. Upload tile-9.png
                2. Upload tile-8.png
                ...
                9. Upload tile-1.png

                Enjoy your professional looking grid!
                Generated by NJTools.xyz (on-device processing).
                `;
                zip.file("READ_ME_INSTRUCTIONS.txt", readme);

                // Generate and download ZIP
                const content = await zip.generateAsync({ type: 'blob' });
                const zipUrl = URL.createObjectURL(content);
                const link = document.createElement('a');
                link.href = zipUrl;
                link.download = `njtools-instagram-grid-${fileName}.zip`;
                link.click();

                setIsProcessing(false);
                setIsDone(true);
                resolve(null);
            };
        });
    };

    return (
        <ToolLayout
            title="Instagram Grid Maker"
            description="Split your images into a perfect 3x3 grid for your Instagram profile instantly. 100% On-Device."
            seoContent={
                /* Enhanced Professional SEO Content for Instagram Grid Maker */
                <div className="space-y-8 text-slate-700 dark:text-slate-300 font-medium">
                    <section>
                        <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-3 italic tracking-tight uppercase">Strategic Profile Branding</h2>
                        <p className="leading-relaxed text-sm">
                            Creating a visually cohesive Instagram profile is crucial for audience engagement.
                            Our <strong className="text-blue-600 dark:text-blue-400">Pro Instagram Grid Maker</strong> takes any standard image and splits it precisely into a 3x3 grid (9 tiles). This allows you to deploy high-impact visual statements that transform your standard grid into a professional brand canvas.
                        </p>
                    </section>

                    {/* Technical Specification Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="p-6 bg-slate-50 dark:bg-slate-900/50 border border-slate-100 dark:border-slate-800 rounded-[2rem]">
                            <h3 className="text-xs font-black uppercase text-blue-600 mb-3 tracking-[0.2em]">High-Res Output</h3>
                            <p className="text-sm leading-relaxed">
                                We export each tile as a high-fidelity <strong className="text-slate-900 dark:text-white">PNG at 1080x1080px</strong>. This ensures maximum sharpness when users view individual posts, adhering to Instagram's optimal resolution standards.
                            </p>
                        </div>
                        <div className="p-6 bg-slate-50 dark:bg-slate-900/50 border border-slate-100 dark:border-slate-800 rounded-[2rem]">
                            <h3 className="text-xs font-black uppercase text-blue-600 mb-3 tracking-[0.2em]">Smart Cropping</h3>
                            <p className="text-sm leading-relaxed">
                                If your source image is not square, our algorithm automatically applies <strong className="text-slate-900 dark:text-white">center-cropping</strong>. This guarantees a balanced 3x3 layout without distorting the composition of your subject.
                            </p>
                        </div>
                    </div>

                    <section className="border-l-4 border-blue-600 pl-6 bg-blue-50/30 dark:bg-blue-900/10 py-4 pr-4 rounded-r-3xl relative overflow-hidden">
                        <div className="absolute top-0 right-0 p-4 opacity-5">
                            <LayoutGrid size={100} className="dark:text-white"/>
                        </div>
                        <h3 className="text-lg font-black text-slate-900 dark:text-white mb-2 italic racking-tight">On-Device Canvas Thread</h3>
                        <p className="text-sm leading-relaxed opacity-90 max-w-2xl">
                            By utilizing browser-native <strong className="text-blue-500">HTML5 Canvas ImageData API</strong>, NJTools isolates the quantization process in a client-side thread. This guarantees 100% privacy, as your source files never leave your machine and are processed without cloud latency.
                        </p>
                    </section>
                </div>
            }
        >
            <Helmet>
                <title>Free Instagram Grid Maker | Split Images into 9 Tiles | NJTools</title>
                <meta name="description" content="Split your photos into a perfect 3x3 grid for Instagram instantly. Get a complete set of high-res PNG tiles in one ZIP file. Private & secure on-device processing." />
                <meta name="keywords" content="instagram grid maker, split image into 9, instagram grid splitter, photo splitter, free instagram tool, private image splitter, NJTools, Niduranga Jayarathna" />
                <link rel="canonical" href="https://njtools.xyz/tools/instagram-grid" />

                <meta property="og:title" content="Pro Instagram Grid Maker | Complete Asset Bundling | NJTools" />
                <meta property="og:description" content="Split your photos into a perfect 3x3 grid for your Instagram profile. 100% private on-device processing." />
                <meta property="og:url" content="https://njtools.xyz/tools/instagram-grid" />
                <meta property="og:type" content="website" />
            </Helmet>

            <div className="max-w-4xl mx-auto space-y-10">
                {!previewUrl ? (
                    <div className="border-2 border-dashed border-slate-200 dark:border-slate-800 rounded-[3rem] p-24 text-center bg-white dark:bg-slate-950 transition-all hover:border-blue-500 group relative">
                        <input type="file" accept="image/*" onChange={handleImageUpload} className="absolute inset-0 opacity-0 cursor-pointer disabled:cursor-not-allowed" disabled={isProcessing}/>
                        <div className="flex flex-col items-center gap-4">
                            <div className="p-6 bg-slate-900 dark:bg-blue-600 rounded-3xl text-white shadow-2xl group-hover:scale-110 transition-transform">
                                <ImageIcon size={40} />
                            </div>
                            <h3 className="text-2xl font-black dark:text-white uppercase italic tracking-tighter text-center">Upload Source Image</h3>
                            <p className="text-slate-500 font-bold text-sm">SVG or High-res PNG works best</p>
                        </div>
                    </div>
                ) : (
                    <div className="bg-white dark:bg-slate-900 p-8 rounded-[3rem] shadow-2xl border border-slate-100 dark:border-slate-800 flex flex-col md:flex-row items-center gap-10 animate-in fade-in slide-in-from-bottom-6 duration-700 relative overflow-hidden">

                        {/* Source Preview with Grid Overlay */}
                        <div className="relative group w-64 h-64 shrink-0 rounded-4xl overflow-hidden shadow-inner border-2 border-white dark:border-slate-700 bg-slate-100 dark:bg-slate-800">
                            <img src={previewUrl} alt="Source" className="w-full h-full object-cover rounded-[1.8rem]" />

                            {/* Grid Overlay */}
                            <div className="absolute inset-2 grid grid-cols-3 grid-rows-3 gap-1 opacity-60 group-hover:opacity-100 transition-opacity">
                                {[...Array(9)].map((_, i) => (
                                    <div key={i} className="border-2 border-dashed border-white/70 backdrop-blur-sm rounded-lg flex items-center justify-center">
                                        <span className="text-white text-3xl font-black drop-shadow-lg">{i+1}</span>
                                    </div>
                                ))}
                            </div>
                        </div>

                        <div className="flex-1 space-y-6 text-center md:text-left relative z-10">
                            <div>
                                <h4 className="text-3xl font-black dark:text-white uppercase italic tracking-tighter">Ready to Splite</h4>
                                <p className="text-slate-500 text-sm font-bold uppercase tracking-widest mt-1">Output: 9 High-Res PNG Tiles (1080x1080px)</p>
                            </div>

                            <div className="flex flex-wrap gap-4 justify-center md:justify-start pt-2">
                                <button
                                    onClick={generateGridFiles}
                                    disabled={isProcessing}
                                    className="bg-blue-600 text-white px-10 py-5 rounded-3xl font-black hover:bg-blue-700 transition active:scale-95 flex items-center gap-3 shadow-2xl shadow-blue-500/20 disabled:opacity-50"
                                >
                                    {isProcessing ? <Loader2 className="animate-spin" size={22} /> : isDone ? <CheckCircle2 size={22} /> : <LayoutGrid size={22} />}
                                    {isProcessing ? 'Processing Canvas...' : isDone ? 'Downloaded Grid ZIP!' : 'Generate 3x3 Grid ZIP'}
                                </button>

                                <button
                                    onClick={() => { setPreviewUrl(null); }}
                                    className="bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 px-7 py-5 rounded-3xl font-black hover:bg-rose-500 hover:text-white transition flex items-center gap-3"
                                >
                                    <RefreshCw size={20} /> Reset
                                </button>
                            </div>
                        </div>
                    </div>
                )}
            </div>

            <canvas ref={canvasRef} className="hidden" />
        </ToolLayout>
    );
};

export default InstagramGridMaker;